Raspberry - Condigure make install script

diff --git a/Raspberry/Makefile b/Raspberry/Makefile
--- a/Raspberry/Makefile
+++ b/Raspberry/Makefile
@@ -1,8 +1,8 @@
-DIR_MAIN		= ./src
-DIR_LIB			= ${DIR_MAIN}/lib
-DIR_INCLUDES	= ${DIR_MAIN}/includes
-DIR_HELPERS		= ${DIR_MAIN}/helpers
-DIR_ASSETS		= ${DIR_MAIN}/assets
+DIR_SRC		= ./src
+DIR_LIB			= ${DIR_SRC}/lib
+DIR_INCLUDES	= ${DIR_SRC}/includes
+DIR_HELPERS		= ${DIR_SRC}/helpers
+DIR_ASSETS		= ${DIR_SRC}/assets
 DIR_IMAGES		= ${DIR_ASSETS}/images
 
 DIR_DISPLAY				= ${DIR_LIB}/LCD_display
@@ -14,13 +14,28 @@ DIR_DISPLAY_GUI			= ${DIR_DISPLAY}/GUI
 DIR_STEPPER		= $(DIR_LIB)/Stepper
 DIR_GPS			= $(DIR_LIB)/GPS
 
-DIR_BIN		= ./bin
+TARGET = torino-ecu
+BUILD_DIR := build
+DEST_DIR := /usr/local/bin
+CONFIG_DIR := /etc/$(TARGET)
+CONFIG_FILE := $(DIR_SRC)/config.ini
+
+# Rules
+all: prepare $(TARGET)
+
+# Pre-build step
+prepare:
+	@echo "Running pre-build scripts..."
+	@mkdir -p $(BUILD_DIR)
+	@echo "Checking dependencies..."
+	@if ! dpkg -s libbcm2835-dev > /dev/null 2>&1; then \
+	    echo "'libbcm2835-dev' is not installed."; \
+	    apt-get install -y libbcm2835-dev; \
+	fi
 
 SRC_C = $(wildcard ${DIR_DISPLAY}/*.c ${DIR_DISPLAY_EPD}/*.c ${DIR_DISPLAY_FONTS}/*.c ${DIR_DISPLAY_GUI}/*.c ${DIR_DISPLAY_CONFIG}/*.c)
-SRC_CPP = $(wildcard ${DIR_MAIN}/*.cpp ${DIR_INCLUDES}/*.cpp ${DIR_HELPERS}/*.cpp ${DIR_IMAGES}/*.cpp ${DIR_STEPPER}/*.cpp ${DIR_GPS}/*.cpp)
-OBJ_O = $(patsubst %.c,${DIR_BIN}/%.o,$(notdir ${SRC_C})) $(patsubst %.cpp,${DIR_BIN}/%.o,$(notdir ${SRC_CPP}))
-
-TARGET = torino-ecu
+SRC_CPP = $(wildcard ${DIR_SRC}/*.cpp ${DIR_INCLUDES}/*.cpp ${DIR_HELPERS}/*.cpp ${DIR_IMAGES}/*.cpp ${DIR_STEPPER}/*.cpp ${DIR_GPS}/*.cpp)
+OBJ_O = $(patsubst %.c,${BUILD_DIR}/%.o,$(notdir ${SRC_C})) $(patsubst %.cpp,${BUILD_DIR}/%.o,$(notdir ${SRC_CPP}))
 
 USELIB = USE_BCM2835_LIB
 #USELIB = USE_WIRINGPI_LIB
@@ -43,39 +58,56 @@ DISPLAY = -I $(DIR_DISPLAY_CONFIG) -I $(DIR_DISPLAY_GUI) -I $(DIR_DISPLAY_EPD) -
 ${TARGET}:${OBJ_O}
 	$(CC) $(CFLAGS) $(OBJ_O) -o $@ $(LIB)
     
-${DIR_BIN}/%.o:$(DIR_MAIN)/%.cpp
-	$(CC) $(CFLAGS) -c $< -o $@ -I $(DIR_MAIN) $(DISPLAY) -I $(DIR_STEPPER) -I $(DIR_GPS) -I $(DIR_HELPERS) -I $(DIR_INCLUDES)
+${BUILD_DIR}/%.o:$(DIR_SRC)/%.cpp
+	$(CC) $(CFLAGS) -c $< -o $@ -I $(DIR_SRC) $(DISPLAY) -I $(DIR_STEPPER) -I $(DIR_GPS) -I $(DIR_HELPERS) -I $(DIR_INCLUDES)
     
-${DIR_BIN}/%.o:$(DIR_DISPLAY)/%.c
+${BUILD_DIR}/%.o:$(DIR_DISPLAY)/%.c
 	$(CC) $(CFLAGS) -c $< -o $@ -I $(DIR_DISPLAY_CONFIG) -I $(DIR_DISPLAY_GUI) -I $(DIR_DISPLAY_EPD)
 
-${DIR_BIN}/%.o:$(DIR_DISPLAY_EPD)/%.c
+${BUILD_DIR}/%.o:$(DIR_DISPLAY_EPD)/%.c
 	$(CC) $(CFLAGS) -c $< -o $@ -I $(DIR_DISPLAY_CONFIG)
     
-${DIR_BIN}/%.o:$(DIR_DISPLAY_FONTS)/%.c
+${BUILD_DIR}/%.o:$(DIR_DISPLAY_FONTS)/%.c
 	$(CC) $(CFLAGS) -c $< -o $@
     
-${DIR_BIN}/%.o:$(DIR_DISPLAY_GUI)/%.c
+${BUILD_DIR}/%.o:$(DIR_DISPLAY_GUI)/%.c
 	$(CC) $(CFLAGS) -c $< -o $@ -I $(DIR_DISPLAY_CONFIG) -I $(DIR_DISPLAY_EPD) -I $(DIR_DISPLAY)
 
-${DIR_BIN}/%.o:$(DIR_DISPLAY_CONFIG)/%.c
+${BUILD_DIR}/%.o:$(DIR_DISPLAY_CONFIG)/%.c
 	$(CC) $(CFLAGS) -c $< -o $@ $(LIB)
 
-${DIR_BIN}/%.o:$(DIR_INCLUDES)/%.cpp
+${BUILD_DIR}/%.o:$(DIR_INCLUDES)/%.cpp
 	$(CC) $(CFLAGS) -c $< -o $@
 
-${DIR_BIN}/%.o:$(DIR_HELPERS)/%.cpp
+${BUILD_DIR}/%.o:$(DIR_HELPERS)/%.cpp
 	$(CC) $(CFLAGS) -c $< -o $@
 
-${DIR_BIN}/%.o:$(DIR_IMAGES)/%.cpp
+${BUILD_DIR}/%.o:$(DIR_IMAGES)/%.cpp
 	$(CC) $(CFLAGS) -c $< -o $@
 
-${DIR_BIN}/%.o:$(DIR_STEPPER)/%.cpp
+${BUILD_DIR}/%.o:$(DIR_STEPPER)/%.cpp
 	$(CC) $(CFLAGS) -c $< -o $@
 
-${DIR_BIN}/%.o:$(DIR_GPS)/%.cpp
+${BUILD_DIR}/%.o:$(DIR_GPS)/%.cpp
 	$(CC) $(CFLAGS) -c $< -o $@ -I $(DIR_INCLUDES)
 	
-clean :
-	rm $(DIR_BIN)/*.* 
-	rm $(TARGET) 
+# Install
+install: all
+	@echo "Installing to $(DEST_DIR)..."
+	@mkdir -p $(DEST_DIR)
+	@cp $(TARGET) $(DEST_DIR)
+	@echo "Copying configuration file to $(CONFIG_DIR)..."
+	@mkdir -p $(CONFIG_DIR)
+	@cp $(CONFIG_FILE) $(CONFIG_DIR)
+	@echo "Copying assets to $(CONFIG_DIR)..."
+	@echo "Running initial setup script..."
+	@cp -R $(DIR_ASSETS) $(CONFIG_DIR)
+	@bash setup.sh $(TARGET) $(DEST_DIR) $(CONFIG_DIR)
+
+# Clean up
+clean:
+	@echo "Cleaning up..."
+	@rm -rf $(BUILD_DIR) $(TARGET)
+
+# Phony targets
+.PHONY: all prepare install clean
